[package]
name = "rust_study"
version = "0.1.0"
authors = ["yynlove <1993208827@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
